// src/App.tsx
import { MouseEvent, useEffect, useMemo, useState } from "react";
import { Menu } from "lucide-react";
import DeviceDdnsPanel from "./components/DeviceDdnsPanel";
import ForwardRulesPanel from "./components/ForwardRulesPanel";
import LogPanel from "./components/LogPanel";
import ReverseProxyPanel from "./components/ReverseProxyPanel";
import RuntimeSettingsPanel from "./components/RuntimeSettingsPanel";
import StatusCard from "./components/StatusCard";
import {
  closeCurrentWindow,
  invokeCommand,
  minimizeCurrentWindow,
  startCurrentWindowDrag,
  toggleMaximizeCurrentWindow,
} from "./lib/tauri";
import type { AppUpdateResult, LanDevice, RuntimeStatus } from "./types";

const emptyStatus: RuntimeStatus = {
  public_ipv4: "",
  public_ipv6: "",
  ddns_status: "",
  last_update_time: "",
  rule_count: 0,
  enabled_rule_count: 0,
  reverse_proxy_rule_count: 0,
  enabled_reverse_proxy_rule_count: 0,
  uptime: 0,
};

function displayValue(value: string): string {
  return value?.trim() ? value : "--";
}

function ipv6PrefixSubtitle(value: string): string {
  const parts = value.split(":");
  if (!value.trim() || parts.length < 4) {
    return "前缀：--";
  }
  return `前缀：${parts.slice(0, 4).join(":")}::/64`;
}

export default function App() {
  const [statusData, setStatusData] = useState<RuntimeStatus>({ ...emptyStatus });
  const [deviceSummary, setDeviceSummary] = useState({ online: 0, total: 0 });
  const [autoStartEnabled, setAutoStartEnabled] = useState(false);
  const [autoStartSaving, setAutoStartSaving] = useState(false);
  const [updateChecking, setUpdateChecking] = useState(false);
  const [appVersion, setAppVersion] = useState("0.1.4");
  const [updateStatusMessage, setUpdateStatusMessage] = useState("");
  const [updateStatusType, setUpdateStatusType] = useState<"normal" | "success" | "error">(
    "normal",
  );

  const disabledRuleCount = Math.max(0, statusData.rule_count - statusData.enabled_rule_count);
  const disabledReverseProxyCount = Math.max(
    0,
    statusData.reverse_proxy_rule_count - statusData.enabled_reverse_proxy_rule_count,
  );

  function ddnsStatusType(): "normal" | "warning" | "error" | "success" {
    if (statusData.ddns_status === "运行中") return "success";
    if (statusData.ddns_status === "未连接") return "warning";
    return "normal";
  }

  const statusCards = useMemo(
    () => [
      {
        title: "公网 IPv4",
        value: displayValue(statusData.public_ipv4),
        subtitle: "运营商：中国电信",
        icon: "globe",
        status: "normal" as const,
      },
      {
        title: "公网 IPv6",
        value: statusData.public_ipv6.trim() ? `${displayValue(statusData.public_ipv6)}/64` : "--",
        subtitle: ipv6PrefixSubtitle(statusData.public_ipv6),
        icon: "ipv6",
        status: "normal" as const,
      },
      {
        title: "DDNS 状态",
        value: statusData.ddns_status || "未连接",
        subtitle: `最后同步：${statusData.last_update_time || "暂无"}`,
        icon: "shield",
        status: ddnsStatusType(),
      },
      {
        title: "转发规则数",
        value: String(statusData.rule_count),
        subtitle: `启用：${statusData.enabled_rule_count}  禁用：${disabledRuleCount}`,
        icon: "rules",
        status: "normal" as const,
      },
      {
        title: "反向代理数",
        value: String(statusData.reverse_proxy_rule_count),
        subtitle: `启用：${statusData.enabled_reverse_proxy_rule_count}  禁用：${disabledReverseProxyCount}`,
        icon: "proxy",
        status: "normal" as const,
      },
      {
        title: "在线设备 / 发现设备",
        value: `${deviceSummary.online} / ${deviceSummary.total}`,
        subtitle: "局域网扫描结果",
        icon: "devices",
        status: "normal" as const,
      },
    ],
    [deviceSummary.online, deviceSummary.total, disabledReverseProxyCount, disabledRuleCount, statusData],
  );

  async function loadRuntimeStatus() {
    try {
      const data = await invokeCommand<RuntimeStatus>("get_runtime_status");
      setStatusData({ ...emptyStatus, ...data });
    } catch {
      setStatusData({ ...emptyStatus });
    }
  }

  async function loadDeviceSummary() {
    try {
      const devices = await invokeCommand<LanDevice[]>("list_lan_devices");
      setDeviceSummary({
        online: devices.filter((device) => device.online).length,
        total: devices.length,
      });
    } catch {
      setDeviceSummary({ online: 0, total: 0 });
    }
  }

  async function loadAutoStart() {
    try {
      setAutoStartEnabled(await invokeCommand<boolean>("get_auto_start"));
    } catch {
      setAutoStartEnabled(false);
    }
  }

  function notifyLogsChanged() {
    window.dispatchEvent(new CustomEvent("homenet:logs-refresh"));
  }

  async function toggleAutoStart(enabled: boolean) {
    const previous = autoStartEnabled;
    setAutoStartEnabled(enabled);
    setAutoStartSaving(true);

    try {
      await invokeCommand("set_auto_start", { enabled });
      notifyLogsChanged();
    } catch (error) {
      setAutoStartEnabled(previous);
      console.warn("设置开机自启动失败:", error);
    } finally {
      setAutoStartSaving(false);
    }
  }

  async function installAppUpdate() {
    if (updateChecking) return;
    setUpdateChecking(true);
    setUpdateStatusType("normal");
    setUpdateStatusMessage("正在检查更新");

    try {
      const result = await invokeCommand<AppUpdateResult>("install_app_update");
      setUpdateStatusMessage(result.message);
      setAppVersion(result.current_version || appVersion);
      setUpdateStatusType(result.status === "installed" ? "success" : "normal");
      notifyLogsChanged();
    } catch (error) {
      setUpdateStatusMessage(`检查更新失败：${String(error)}`);
      setUpdateStatusType("error");
    } finally {
      setUpdateChecking(false);
    }
  }

  async function startWindowDrag(event: MouseEvent<HTMLElement>) {
    if (event.button !== 0) return;
    const target = event.target as HTMLElement | null;
    if (target?.closest("button, input, select, textarea, a, label")) return;
    try {
      await startCurrentWindowDrag();
    } catch (error) {
      console.warn("启动窗口拖动失败:", error);
    }
  }

  useEffect(() => {
    loadRuntimeStatus();
    loadDeviceSummary();
    loadAutoStart();
    window.addEventListener("homenet:refresh-status", loadRuntimeStatus);
    window.addEventListener("homenet:devices-refresh", loadDeviceSummary);

    const runtimeTimer = window.setInterval(loadRuntimeStatus, 10000);
    const deviceTimer = window.setInterval(loadDeviceSummary, 30000);

    return () => {
      window.removeEventListener("homenet:refresh-status", loadRuntimeStatus);
      window.removeEventListener("homenet:devices-refresh", loadDeviceSummary);
      window.clearInterval(runtimeTimer);
      window.clearInterval(deviceTimer);
    };
  }, []);

  return (
    <div className="window-frame">
      <header className="titlebar" onMouseDown={startWindowDrag}>
        <div className="titlebar-left">
          <button className="menu-button" type="button" aria-label="菜单" onMouseDown={(event) => event.stopPropagation()}>
            <Menu size={21} strokeWidth={2.1} />
          </button>
          <h1>HomeNet</h1>
          {updateStatusMessage ? (
            <span className={`update-status update-${updateStatusType}`}>{updateStatusMessage}</span>
          ) : null}
        </div>

        <div className="window-controls">
          <button
            className="window-control control-minimize"
            type="button"
            aria-label="最小化"
            onClick={minimizeCurrentWindow}
            onMouseDown={(event) => event.stopPropagation()}
          />
          <button
            className="window-control control-maximize"
            type="button"
            aria-label="最大化"
            onClick={toggleMaximizeCurrentWindow}
            onMouseDown={(event) => event.stopPropagation()}
          />
          <button
            className="window-control control-close"
            type="button"
            aria-label="关闭"
            onClick={closeCurrentWindow}
            onMouseDown={(event) => event.stopPropagation()}
          />
        </div>
      </header>

      <main className="main-content">
        <section className="section-cards" aria-label="运行状态">
          {statusCards.map((card) => (
            <StatusCard key={card.title} {...card} />
          ))}
        </section>

        <section className="dashboard-grid" aria-label="网络配置">
          <ForwardRulesPanel />
          <DeviceDdnsPanel className="device-ddns-column" />
          <ReverseProxyPanel />
        </section>

        <section className="bottom-grid" aria-label="日志与设置">
          <LogPanel />
          <RuntimeSettingsPanel
            uptime={statusData.uptime}
            version={appVersion}
            autoStartEnabled={autoStartEnabled}
            autoStartSaving={autoStartSaving}
            updateChecking={updateChecking}
            onToggleAutostart={toggleAutoStart}
            onCheckUpdate={installAppUpdate}
          />
        </section>
      </main>
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { Menu } from "@lucide/vue";
import StatusCard from "./components/StatusCard.vue";
import DeviceDdnsPanel from "./components/DeviceDdnsPanel.vue";
import ForwardRulesPanel from "./components/ForwardRulesPanel.vue";
import LogPanel from "./components/LogPanel.vue";
import ReverseProxyPanel from "./components/ReverseProxyPanel.vue";
import RuntimeSettingsPanel from "./components/RuntimeSettingsPanel.vue";
import type { AppUpdateResult, LanDevice, RuntimeStatus } from "./types";

const emptyStatus: RuntimeStatus = {
  public_ipv4: "",
  public_ipv6: "",
  ddns_status: "",
  last_update_time: "",
  rule_count: 0,
  enabled_rule_count: 0,
  reverse_proxy_rule_count: 0,
  enabled_reverse_proxy_rule_count: 0,
  uptime: 0,
};

const statusData = ref<RuntimeStatus>({ ...emptyStatus });
const deviceSummary = ref({ online: 0, total: 0 });
const autoStartEnabled = ref(false);
const autoStartSaving = ref(false);
const updateChecking = ref(false);
const appVersion = ref("0.1.4");
const updateStatusMessage = ref("");
const updateStatusType = ref<"normal" | "success" | "error">("normal");

let runtimeTimer: ReturnType<typeof setInterval> | null = null;
let deviceTimer: ReturnType<typeof setInterval> | null = null;

const disabledRuleCount = computed(() =>
  Math.max(0, statusData.value.rule_count - statusData.value.enabled_rule_count),
);
const disabledReverseProxyCount = computed(() =>
  Math.max(
    0,
    statusData.value.reverse_proxy_rule_count -
      statusData.value.enabled_reverse_proxy_rule_count,
  ),
);

const statusCards = computed(() => [
  {
    title: "公网 IPv4",
    value: displayValue(statusData.value.public_ipv4),
    subtitle: "运营商：中国电信",
    icon: "globe",
    status: "normal" as const,
  },
  {
    title: "公网 IPv6",
    value: statusData.value.public_ipv6.trim()
      ? `${displayValue(statusData.value.public_ipv6)}/64`
      : "--",
    subtitle: ipv6PrefixSubtitle(statusData.value.public_ipv6),
    icon: "ipv6",
    status: "normal" as const,
  },
  {
    title: "DDNS 状态",
    value: statusData.value.ddns_status || "未连接",
    subtitle: `最后同步：${statusData.value.last_update_time || "暂无"}`,
    icon: "shield",
    status: ddnsStatusType(),
  },
  {
    title: "转发规则数",
    value: String(statusData.value.rule_count),
    subtitle: `启用：${statusData.value.enabled_rule_count}　禁用：${disabledRuleCount.value}`,
    icon: "rules",
    status: "normal" as const,
  },
  {
    title: "反向代理数",
    value: String(statusData.value.reverse_proxy_rule_count),
    subtitle: `启用：${statusData.value.enabled_reverse_proxy_rule_count}　禁用：${disabledReverseProxyCount.value}`,
    icon: "proxy",
    status: "normal" as const,
  },
  {
    title: "在线设备 / 发现设备",
    value: `${deviceSummary.value.online} / ${deviceSummary.value.total}`,
    subtitle: "局域网扫描结果",
    icon: "devices",
    status: "normal" as const,
  },
]);

function displayValue(value: string): string {
  return value?.trim() ? value : "--";
}

function ipv6PrefixSubtitle(value: string): string {
  const parts = value.split(":");
  if (!value.trim() || parts.length < 4) {
    return "前缀：--";
  }
  return `前缀：${parts.slice(0, 4).join(":")}::/64`;
}

function ddnsStatusType(): "normal" | "warning" | "error" | "success" {
  if (statusData.value.ddns_status === "运行中") return "success";
  if (statusData.value.ddns_status === "未连接") return "warning";
  return "normal";
}

async function loadRuntimeStatus() {
  try {
    const data = await invoke<RuntimeStatus>("get_runtime_status");
    statusData.value = {
      ...emptyStatus,
      ...data,
    };
  } catch {
    statusData.value = { ...emptyStatus };
  }
}

async function loadDeviceSummary() {
  try {
    const devices = await invoke<LanDevice[]>("list_lan_devices");
    deviceSummary.value = {
      online: devices.filter((device) => device.online).length,
      total: devices.length,
    };
  } catch {
    deviceSummary.value = { online: 0, total: 0 };
  }
}

async function loadAutoStart() {
  try {
    autoStartEnabled.value = await invoke<boolean>("get_auto_start");
  } catch {
    autoStartEnabled.value = false;
  }
}

function notifyLogsChanged() {
  window.dispatchEvent(new CustomEvent("homenet:logs-refresh"));
}

async function toggleAutoStart(enabled: boolean) {
  const previous = autoStartEnabled.value;
  autoStartEnabled.value = enabled;
  autoStartSaving.value = true;

  try {
    await invoke("set_auto_start", { enabled });
    notifyLogsChanged();
  } catch (e) {
    autoStartEnabled.value = previous;
    console.warn("设置开机自启动失败:", e);
  } finally {
    autoStartSaving.value = false;
  }
}

async function installAppUpdate() {
  if (updateChecking.value) return;
  updateChecking.value = true;
  updateStatusType.value = "normal";
  updateStatusMessage.value = "正在检查更新";

  try {
    const result = await invoke<AppUpdateResult>("install_app_update");
    updateStatusMessage.value = result.message;
    appVersion.value = result.current_version || appVersion.value;
    updateStatusType.value = result.status === "installed" ? "success" : "normal";
    notifyLogsChanged();
  } catch (e) {
    updateStatusMessage.value = `检查更新失败：${String(e)}`;
    updateStatusType.value = "error";
  } finally {
    updateChecking.value = false;
  }
}

async function minimizeWindow() {
  const appWindow = currentTauriWindow();
  if (!appWindow) return;
  await appWindow.minimize();
}

async function maximizeWindow() {
  const appWindow = currentTauriWindow();
  if (!appWindow) return;
  if (await appWindow.isMaximized()) {
    await appWindow.unmaximize();
  } else {
    await appWindow.maximize();
  }
}

async function closeWindow() {
  const appWindow = currentTauriWindow();
  if (!appWindow) return;
  await appWindow.close();
}

async function startWindowDrag(event: MouseEvent) {
  if (event.button !== 0) return;
  const target = event.target as HTMLElement | null;
  if (target?.closest("button, input, select, textarea, a, label")) return;
  try {
    const appWindow = currentTauriWindow();
    if (!appWindow) return;
    await appWindow.startDragging();
  } catch (e) {
    console.warn("启动窗口拖动失败:", e);
  }
}

function currentTauriWindow() {
  if (!("__TAURI_INTERNALS__" in window)) return null;
  try {
    return getCurrentWindow();
  } catch {
    return null;
  }
}

onMounted(() => {
  loadRuntimeStatus();
  loadDeviceSummary();
  loadAutoStart();
  window.addEventListener("homenet:refresh-status", loadRuntimeStatus);
  window.addEventListener("homenet:devices-refresh", loadDeviceSummary);
  runtimeTimer = setInterval(loadRuntimeStatus, 10000);
  deviceTimer = setInterval(loadDeviceSummary, 30000);
});

onUnmounted(() => {
  window.removeEventListener("homenet:refresh-status", loadRuntimeStatus);
  window.removeEventListener("homenet:devices-refresh", loadDeviceSummary);
  if (runtimeTimer !== null) {
    clearInterval(runtimeTimer);
    runtimeTimer = null;
  }
  if (deviceTimer !== null) {
    clearInterval(deviceTimer);
    deviceTimer = null;
  }
});
</script>

<template>
  <div class="window-frame">
    <header class="titlebar" @mousedown="startWindowDrag">
      <div class="titlebar-left">
        <button class="menu-button" type="button" aria-label="菜单" @mousedown.stop>
          <Menu :size="21" :stroke-width="2.1" />
        </button>
        <h1>HomeNet</h1>
        <span
          v-if="updateStatusMessage"
          class="update-status"
          :class="`update-${updateStatusType}`"
        >
          {{ updateStatusMessage }}
        </span>
      </div>

      <div class="window-controls">
        <button
          class="window-control control-minimize"
          type="button"
          aria-label="最小化"
          @click="minimizeWindow"
          @mousedown.stop
        ></button>
        <button
          class="window-control control-maximize"
          type="button"
          aria-label="最大化"
          @click="maximizeWindow"
          @mousedown.stop
        ></button>
        <button
          class="window-control control-close"
          type="button"
          aria-label="关闭"
          @click="closeWindow"
          @mousedown.stop
        ></button>
      </div>
    </header>

    <main class="main-content">
      <section class="section-cards" aria-label="运行状态">
        <StatusCard
          v-for="card in statusCards"
          :key="card.title"
          :title="card.title"
          :value="card.value"
          :subtitle="card.subtitle"
          :icon="card.icon"
          :status="card.status"
        />
      </section>

      <section class="dashboard-grid" aria-label="网络配置">
        <ForwardRulesPanel />
        <DeviceDdnsPanel class="device-ddns-column" />
        <ReverseProxyPanel />
      </section>

      <section class="bottom-grid" aria-label="日志与设置">
        <LogPanel />
        <RuntimeSettingsPanel
          :uptime="statusData.uptime"
          :version="appVersion"
          :auto-start-enabled="autoStartEnabled"
          :auto-start-saving="autoStartSaving"
          :update-checking="updateChecking"
          @toggle-autostart="toggleAutoStart"
          @check-update="installAppUpdate"
        />
      </section>
    </main>
  </div>
</template>

<style>
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --color-window-bg: #f7f9fc;
  --color-card-bg: #ffffff;
  --color-primary: #1769f6;
  --color-primary-hover: #0d58dd;
  --color-primary-soft: #eaf2ff;
  --color-text-primary: #101522;
  --color-text-secondary: #4e5969;
  --color-text-muted: #7b8495;
  --color-border: #dfe6ef;
  --color-border-strong: #cbd6e5;
  --color-input-bg: #ffffff;
  --color-success: #12a150;
  --color-success-soft: #e9f8ef;
  --color-warning: #d97706;
  --color-warning-soft: #fff6df;
  --color-error: #dc2626;
  --shadow-panel: 0 9px 24px rgba(34, 48, 76, 0.06);
  --shadow-soft: 0 2px 8px rgba(28, 42, 66, 0.06);
  --radius-sm: 4px;
  --radius-md: 8px;
  --titlebar-height: 52px;
}

html,
body {
  height: 100%;
  overflow: hidden;
}

body {
  font-family:
    "Microsoft YaHei UI",
    "Microsoft YaHei",
    "Segoe UI",
    -apple-system,
    BlinkMacSystemFont,
    sans-serif;
  font-size: 12px;
  line-height: 1.42;
  color: var(--color-text-primary);
  background: #edf2f8;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#app {
  width: 100vw;
  height: 100vh;
  overflow: hidden;
}

button,
input,
select {
  font: inherit;
}

button {
  cursor: pointer;
}

input,
select {
  min-width: 0;
}
</style>

<style scoped>
.window-frame {
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  border: 0;
  border-radius: 0;
  background: var(--color-window-bg);
  box-shadow: none;
}

.titlebar {
  height: var(--titlebar-height);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 13px 0 18px;
  border-bottom: 1px solid rgba(222, 229, 239, 0.95);
  background: rgba(255, 255, 255, 0.9);
  backdrop-filter: blur(10px);
}

.titlebar-left {
  min-width: 0;
  display: flex;
  align-items: center;
  gap: 13px;
}

.menu-button {
  width: 24px;
  height: 24px;
  display: grid;
  place-items: center;
  border: 0;
  border-radius: 5px;
  background: transparent;
  color: #344052;
}

.menu-button:hover {
  background: #eef3f9;
}

.titlebar h1 {
  color: #101522;
  font-size: 15px;
  font-weight: 800;
  letter-spacing: 0;
  white-space: nowrap;
}

.update-status {
  max-width: 450px;
  overflow: hidden;
  color: #667085;
  font-size: 12px;
  font-weight: 700;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.update-success {
  color: #15803d;
}

.update-error {
  color: #b91c1c;
}

.window-controls {
  display: flex;
  align-items: center;
  gap: 22px;
  height: 100%;
}

.window-control {
  position: relative;
  width: 28px;
  height: 28px;
  border: 0;
  border-radius: 4px;
  background: transparent;
}

.window-control:hover {
  background: #edf2f8;
}

.control-close:hover {
  background: #ef4444;
}

.control-minimize::before,
.control-maximize::before,
.control-close::before,
.control-close::after {
  content: "";
  position: absolute;
  display: block;
  background: #111827;
}

.control-minimize::before {
  left: 9px;
  right: 9px;
  top: 15px;
  height: 1.8px;
}

.control-maximize::before {
  left: 9px;
  top: 8px;
  width: 10px;
  height: 10px;
  border: 1.8px solid #111827;
  background: transparent;
}

.control-close::before,
.control-close::after {
  left: 13px;
  top: 7px;
  width: 1.7px;
  height: 15px;
  border-radius: 999px;
}

.control-close::before {
  transform: rotate(45deg);
}

.control-close::after {
  transform: rotate(-45deg);
}

.control-close:hover::before,
.control-close:hover::after {
  background: #ffffff;
}

.main-content {
  height: calc(100vh - var(--titlebar-height));
  display: grid;
  grid-template-rows: 106px minmax(0, 1fr) minmax(150px, 0.34fr);
  gap: 12px;
  padding: 6px 18px 18px;
  overflow: hidden;
}

.section-cards {
  min-width: 0;
  display: grid;
  grid-template-columns: 1.2fr 1.3fr 1.05fr 0.95fr 0.95fr 1fr;
  gap: 8px;
}

.dashboard-grid {
  min-height: 0;
  display: grid;
  grid-template-columns: minmax(560px, 0.95fr) minmax(620px, 1.05fr);
  grid-template-rows: minmax(0, 1fr) minmax(0, 1fr);
  gap: 12px;
}

.device-ddns-column {
  grid-column: 2;
  grid-row: 1 / span 2;
}

.bottom-grid {
  min-height: 0;
  display: grid;
  grid-template-columns: minmax(0, 1fr) 198px;
  gap: 12px;
}
</style>
